import { createRequestHandler, type ServerBuild } from "@remix-run/cloudflare";
// build/server/index.js is generated by \`pnpm build\`. Wrangler bundles
// this entry at deploy time, so the import resolves then. Suppressed
// because tsc/IDE may not see the file before the first build.
// @ts-ignore -- generated at build time
import * as serverBuild from "./build/server";

const handleRequest = createRequestHandler(
  serverBuild as unknown as ServerBuild,
  process.env.NODE_ENV,
);

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext) {
    return handleRequest(request, {
      // Mirror the PlatformProxy shape declared in load-context.ts. In
      // production the env/ctx come from the Worker runtime; the cf
      // properties come from the inbound request.
      cloudflare: {
        env,
        ctx,
        cf: request.cf,
        caches,
      } as never,
    });
  },
};
